update pre-commit hook

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,9 +1,14 @@
 #!/bin/sh
-if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
-    exit 1
+if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|change)(\(.+?\))?: .{1,}$"; then
+    echo "Commit messages should start with feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|change" >&2
+    echo "Example -> docs: Update README" >&2
+    echo "Automatically prepending 'change:' to commit msg " >&2
+    OLDMSG=$(cat "${1}")
+    echo ${OLDMSG} | sed -e 's/^/change\: /'
+    cat "${1}" 
+    exit 0
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
-    echo "Aborting commit. Your commit message is too long." >&2
+    echo "Aborting commit: Commit message too long.  88 Characters is max length." >&2
     exit 1
 fi
